# Site settings
name: Richard Amador
email: richard.amador.jr@gmail.com
#canonical_url: https://richamador.com
keywords: "Product Manager, Design, Ruby, Startups, Agile"
skills: "Product Manager in Jersey City, NJ"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/richard-amador-07585622
  # - title: medium
  #   url: https://medium.com/@cgroom
  # - title: twitter
  #   url: https://twitter.com/chuck_groom
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 116466
  primary-rgb: "33, 150, 243"
  secondary: D9B08C
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
